=== cassiofariasmachado/BancoDeDadosII_CampeonatoBrasileiro/banco_de_dados_II-trabalho2/campeonato.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
	<!-- Elemento Complexo Nome -->
    <xs:simpleType name="tipoNome">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    	
    <!-- Elemento Complexo Posição -->
    <xs:element name="posicao">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Posições -->
    <xs:element name="posicoes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="posicao" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Jogador -->
    <xs:element name="jogador">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="idPosicao" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Diretor -->
    <xs:element name="diretor">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Diretores-->
    <xs:element name="diretores">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="diretor" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Patrocinador -->
    <xs:element name="patrocinador">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Patrocinadores-->
    <xs:element name="patrocinadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="patrocinador" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo TorcidaOrganizada -->
    <xs:element name="torcidaOrganizada">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>    
    </xs:element>
    
    <!-- Elemento Complexo TorcidasOrganizadas -->
    <xs:element name="torcidasOrganizadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="torcidaOrganizada" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
	<!-- Elemento Complexo Clube-->
    <xs:element name="clube">
        <xs:complexType>
            <xs:sequence>
				<xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="jogador"/>
                <xs:element ref="torcidaOrganizada"/>
                <xs:element ref="tecnico"/>
                <xs:element ref="diretores"/>
                <xs:element ref="patrocinadores"/>
                <xs:element ref="posicoes"/>
            </xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nome" type="tipoNome" use="required" />
        </xs:complexType>
    </xs:element>
	
	<!-- Elemento Complexo Clubes-->
    <xs:element name="clubes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="clube" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo ClassificacaoRodada -->
    <xs:element name="classificacaoRodada">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required" />
            <xs:attribute name="idCampeonato" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="idRodada" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="posicao" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="idClube" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo ClassificacoesRodadas -->
    <xs:element name="classificacoesRodadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="classificacaoRodada" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
		
    <!-- Elemento Complexo Jogos -->
    <xs:element name="jogos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clube1Gol" type="xs:integer"/>
                <xs:element name="clube2Gol" type="xs:integer"/>
                <xs:element name="clube1Ponto" type="xs:integer"/>
                <xs:element name="clube2Ponto" type="xs:integer"/>
                <xs:element name="clube1Amarelo" type="xs:integer"/>
                <xs:element name="clube2Amarelo" type="xs:integer"/>
                <xs:element name="clube1Vermelho" type="xs:integer"/>
                <xs:element name="clube2Vermelho" type="xs:integer"/>
            </xs:sequence>
            <xs:attribute name="idCampeonato" type="xs:positiveInteger" use="required" />
            <xs:attribute name="idRodada" type="xs:positiveInteger" use="required" />
            <xs:attribute name="idClube1" type="xs:positiveInteger" use="required" />
            <xs:attribute name="idClube2" type="xs:positiveInteger" use="required" />
            <xs:attribute name="id" type="xs:positiveInteger" use="required" />
        </xs:complexType>
    </xs:element>

	<!-- Elemento Complexo Rodadas -->
    <xs:element name="rodadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="jogos" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="classificacoesRodadas" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
            <xs:attribute name="artilheiro" type="xs:positiveInteger" use="optional"/>
            <xs:attribute name="totalJogos" type="xs:positiveInteger" use="optional"/>
            <xs:attribute name="totalAmarelos" type="xs:positiveInteger" use="optional"/>
            <xs:attribute name="totalVermelhos" type="xs:positiveInteger" use="optional"/>
            <xs:attribute name="totalGols" type="xs:positiveInteger" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo ClassificacaoGeral-->
    <xs:element name="classificacaoGeral">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="posicaoClassificacao" type="xs:positiveInteger"/>
                <xs:element name="idClube" type="xs:positiveInteger"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo ClassificaçõesGerais -->
    <xs:element name="classificacoesGerais">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="classificacaoGeral" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo Tecnico-->
    <xs:element name="tecnico">
        <xs:complexType>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo ClubeDiretor-->
    <xs:element name="clubeDiretor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="diretor" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="clube" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Elemento Complexo ClubePatrocinador-->
    <xs:element name="clubePatrocinador">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="patrocinador" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="clube" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
	
	<!-- Elemento Complexo Campeonato-->
    <xs:element name="campeonato">
        <xs:complexType>
            <xs:sequence>
				<xs:element name="ano" type="xs:positiveInteger"/>
				<xs:element name="nroClubes" type="xs:positiveInteger"/>
                <xs:element ref="clubes" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="rodadas" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="classificacoesGerais" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
			<xs:attribute name="id" type="xs:positiveInteger" use="required" />
			<xs:attribute name="nome" type="tipoNome" use="optional" />
        </xs:complexType>
    </xs:element>

    <!-- Root -->
    <xs:element name="campeonatos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="campeonato" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    
        <!-- PKs -->
        <xs:key name="pk_posicao">
            <xs:selector xpath=".//posicao"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_jogador">
            <xs:selector xpath=".//jogador"/>
            <xs:field xpath="@id"/>
        </xs:key> 
        
        <xs:key name="pk_diretor">
            <xs:selector xpath=".//diretor"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_tecnico">
            <xs:selector xpath=".//tecnico"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_patrocinador">
            <xs:selector xpath=".//patrocinador"/>
            <xs:field xpath="@id"/>
        </xs:key>    
        
        <xs:key name="pk_classificacao_geral">
            <xs:selector xpath=".//classificacaoGeral"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_clubeDiretor">
            <xs:selector xpath=".//clubeDiretor"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_clubePatrocinador">
            <xs:selector xpath=".//clubePatrocinador"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_clube">
            <xs:selector xpath=".//clube"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_campeonato">
            <xs:selector xpath=".//campeonato"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_rodada">
            <xs:selector xpath=".//rodadas"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_jogos">
            <xs:selector xpath=".//jogos"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        <xs:key name="pk_torcidaOrganizada">
            <xs:selector xpath=".//torcidaOrganizada"/>
            <xs:field xpath="@id"/>
        </xs:key>
        
        
        
        <!-- Refs PKs -->
        <xs:keyref name="fk_jogador_posicao" refer="pk_posicao">
            <xs:selector xpath="jogador"/>
            <xs:field xpath="idPosicao"/>
        </xs:keyref>
        
        <xs:keyref name="fk_classificacaoGeral_campeonato" refer="pk_campeonato">
            <xs:selector xpath="classificacaoGeral"/>
            <xs:field xpath="idCampeonato"/>
        </xs:keyref>
        
        <xs:keyref name="fk_classificacaoGeral_clube" refer="pk_clube">
            <xs:selector xpath="classificacaoGeral"/>
            <xs:field xpath="idClube"/>
        </xs:keyref>
        
        <xs:keyref name="fk_jogos_campeonato" refer="pk_campeonato">
            <xs:selector xpath="jogos"/>
            <xs:field xpath="idCampeonato"/>
        </xs:keyref>   
        
        <xs:keyref name="fk_jogos_clube1" refer="pk_clube">
            <xs:selector xpath="jogos"/>
            <xs:field xpath="idClube1"/>
        </xs:keyref> 
        
        <xs:keyref name="fk_jogos_clube2" refer="pk_clube">
            <xs:selector xpath="jogos"/>
            <xs:field xpath="idClube2"/>
        </xs:keyref> 
        
        <xs:keyref name="fk_rodadas_campeonato" refer="pk_campeonato">
            <xs:selector xpath="rodadas"/>
            <xs:field xpath="idCampeonato"/>
        </xs:keyref> 
        
        <xs:keyref name="fk_rodadas_jogador" refer="pk_jogador">
            <xs:selector xpath="rodadas"/>
            <xs:field xpath="Artilheiro"/>
        </xs:keyref> 
        
        <xs:keyref name="fk_classificacaorodada_campeonato" refer="pk_campeonato">
            <xs:selector xpath="classificacaoRodada"/>
            <xs:field xpath="idCampeonato"/>
        </xs:keyref>
        
        <xs:keyref name="fk_classificacaorodada_rodada" refer="pk_rodada">
            <xs:selector xpath="classificacaoRodada"/>
            <xs:field xpath="idRodada"/>
        </xs:keyref> 
        
        <xs:keyref name="fk_classificacaorodada_clube" refer="pk_clube">
            <xs:selector xpath="classificacaoRodada"/>
            <xs:field xpath="idClube"/>
        </xs:keyref> 
        
    </xs:element>  
</xs:schema>

=== cassiofariasmachado/BancoDeDadosII_CampeonatoBrasileiro/banco_de_dados_II-trabalho2/campeonato-brasileiro-campeonato1.xml
<?xml version="1.0" encoding="UTF-8"?>
<campeonatos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Cassio/Documents/git/banco_de_dados_II-campeonato_brasileiro/banco_de_dados_II-trabalho2/campeonato.xsd">
 <campeonato id="1">
  <ano>2017</ano>
  <nroClubes>1</nroClubes>
  <clubes>
   <clube id="50" nome="Internacional">
    <jogador id="1" idPosicao="1"/>
    <jogador id="2" idPosicao="1"/>
    <jogador id="3" idPosicao="1"/>
    <jogador id="4" idPosicao="1"/>
    <jogador id="5" idPosicao="1"/>
    <jogador id="6" idPosicao="1"/>
    <jogador id="7" idPosicao="1"/>
    <jogador id="8" idPosicao="1"/>
    <jogador id="9" idPosicao="1"/>
    <jogador id="10" idPosicao="1"/>
    <jogador id="11" idPosicao="1"/>
    <jogador id="12" idPosicao="1"/>
    <jogador id="13" idPosicao="1"/>
    <jogador id="14" idPosicao="1"/>
    <jogador id="15" idPosicao="1"/>
    <jogador id="16" idPosicao="1"/>
    <torcidaOrganizada nome="Camisa 12" id="1"/>
    <tecnico nome="Celso Roth" id="1"/>
    <diretores>
     <diretor nome="Vitorio Piffero" id="1"/>
    </diretores>
    <patrocinadores>
     <patrocinador nome="Banrisul" id="1"/>
     <patrocinador nome="Nike" id="2"/>
    </patrocinadores>
    <posicoes>
     <posicao nome="Zagueiro" id="1"/>
    </posicoes>
   </clube>
  </clubes>
  <rodadas id="1">
   <jogos idCampeonato="1" idRodada="1" idClube1="1" idClube2="1" id="1">
    <clube1Gol>50</clube1Gol>
    <clube2Gol>50</clube2Gol>
    <clube1Ponto>50</clube1Ponto>
    <clube2Ponto>50</clube2Ponto>
    <clube1Amarelo>50</clube1Amarelo>
    <clube2Amarelo>50</clube2Amarelo>
    <clube1Vermelho>50</clube1Vermelho>
    <clube2Vermelho>50</clube2Vermelho>
   </jogos>
   <jogos idCampeonato="1" idRodada="50" idClube1="1" idClube2="1" id="50">
    <clube1Gol>1</clube1Gol>
    <clube2Gol>1</clube2Gol>
    <clube1Ponto>50</clube1Ponto>
    <clube2Ponto>50</clube2Ponto>
    <clube1Amarelo>50</clube1Amarelo>
    <clube2Amarelo>50</clube2Amarelo>
    <clube1Vermelho>50</clube1Vermelho>
    <clube2Vermelho>50</clube2Vermelho>
   </jogos>
   <classificacoesRodadas>
    <classificacaoRodada id="1" idCampeonato="50" idRodada="50" posicao="50" idClube="50"/>
   </classificacoesRodadas>
  </rodadas>
  <classificacoesGerais>
    <classificacaoGeral id="1">
        <posicaoClassificacao>1</posicaoClassificacao>
        <idClube>1</idClube>
      </classificacaoGeral>
   </classificacoesGerais>
 </campeonato>
</campeonatos>
